In [9]:
import numpy as np
x = np.array([[2, 1834, 1],[3, 1534, 2],[2, 962, 3]])
x

array([[   2, 1834,    1],
       [   3, 1534,    2],
       [   2,  962,    3]])

In [10]:
y = [8500, 9600, 258800]
y

[8500, 9600, 258800]

In [11]:
transpose_x = x.transpose()
transpose_x

array([[   2,    3,    2],
       [1834, 1534,  962],
       [   1,    2,    3]])

In [12]:
multi_transpose_x_to_x = np.dot(transpose_x, x)
multi_transpose_x_to_x

array([[     17,   10194,      14],
       [  10194, 6642156,    7788],
       [     14,    7788,      14]])

In [13]:
inverse_of_multi_transpose_x_to_x = np.linalg.inv(multi_transpose_x_to_x)
inverse_of_multi_transpose_x_to_x

array([[ 2.02512573e+00, -2.10946682e-03, -8.51659467e-01],
       [-2.10946682e-03,  2.63025789e-06,  6.46291938e-04],
       [-8.51659467e-01,  6.46291938e-04,  5.63565067e-01]])

In [14]:
multiplication_transposed_x_y = np.dot(transpose_x, y)
multiplication_transposed_x_y

array([   563400, 279281000,    804100])

In [15]:
theta = np.dot(inverse_of_multi_transpose_x_to_x, multiplication_transposed_x_y)
theta

array([-1.32997548e+05,  6.57907908e+01,  1.53834785e+05])