In [2]:
import numpy as np
import pandas as pd 
import matplotlib.pyplot as plt 
%matplotlib inline
import matplotlib as mpl 
mpl.rcParams['figure.dpi'] = 400 

In [3]:
df = pd.read_csv('../data/chap_1_cleaned_data.csv')
df.head(5)

ID  LIMIT_BAL  SEX  EDUCATION  MARRIAGE  AGE  PAY_1  PAY_2  \
0  798fc410-45c1      20000    2          2         1   24      2      2   
1  8a8c8f3b-8eb4     120000    2          2         2   26     -1      2   
2  85698822-43f5      90000    2          2         2   34      0      0   
3  0737c11b-be42      50000    2          2         1   37      0      0   
4  3b7f77cc-dbc0      50000    1          2         1   57     -1      0   

   PAY_3  PAY_4  ...  PAY_AMT3  PAY_AMT4  PAY_AMT5  PAY_AMT6  \
0     -1     -1  ...         0         0         0         0   
1      0      0  ...      1000      1000         0      2000   
2      0      0  ...      1000      1000      1000      5000   
3      0      0  ...      1200      1100      1069      1000   
4     -1      0  ...     10000      9000       689       679   

   default payment next month  EDUCATION_CAT  graduate school  high school  \
0                           1     university                0            0   
1                           1     university                0            0   
2                           0     university                0            0   
3                           0     university                0            0   
4                           0     university                0            0   

   others  university  
0       0           1  
1       0           1  
2       0           1  
3       0           1  
4       0           1  

[5 rows x 30 columns]

In [4]:
df['default payment next month'].mean()

0.2217971797179718

In [6]:
df.groupby('default payment next month')['ID'].count()

default payment next month
0    20750
1     5914
Name: ID, dtype: int64

In [7]:
from sklearn.linear_model import LogisticRegression

In [9]:
my_lr = LogisticRegression()
my_lr

LogisticRegression()

In [10]:
# with whole parameters
my_new_lr = LogisticRegression(penalty='l2', dual=False,
                               tol=0.0001, C=1.0, fit_intercept=True,
                               intercept_scaling=1, class_weight=None,
                               random_state=None, solver='lbfgs',
                               max_iter=100, multi_class='auto',
                               verbose=0, warm_start=False,
                               n_jobs=None, l1_ratio=None)
my_new_lr 

LogisticRegression()

In [11]:
my_new_lr.C = 0.1
my_new_lr.solver = 'liblinear'

In [12]:
my_new_lr

LogisticRegression(C=0.1, solver='liblinear')

In [13]:
X = df['EDUCATION'][0:10].values.reshape(-1,1)
X

array([[2],
       [2],
       [2],
       [2],
       [2],
       [1],
       [1],
       [2],
       [3],
       [3]])

In [14]:
y = df['default payment next month'][0:10].values
y

array([1, 1, 0, 0, 0, 0, 0, 0, 0, 0])

In [15]:
my_new_lr.fit(X, y)

LogisticRegression(C=0.1, solver='liblinear')

In [16]:
new_X = df['EDUCATION'][10:20].values.reshape(-1,1)
new_X

array([[3],
       [1],
       [2],
       [2],
       [1],
       [3],
       [1],
       [1],
       [1],
       [3]])

In [17]:
my_new_lr.predict(new_X)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [18]:
df['default payment next month'][10:20].values

array([0, 0, 0, 1, 0, 0, 1, 0, 0, 0])